# Generated by Django 4.2.9 on 2026-03-20 01:56

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (minimum 2 characters)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='URL-friendly version of the name', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-news')", max_length=50)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=320)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News title (minimum 10 characters)', max_length=250, validators=[django.core.validators.MinLengthValidator(10)])),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL-friendly title', max_length=250, unique_for_date='publish')),
                ('body', ckeditor.fields.RichTextField(help_text='Main news content with rich formatting')),
                ('summary', models.TextField(blank=True, help_text='Brief summary for preview (max 500 characters)', max_length=500)),
                ('news_type', models.CharField(choices=[('general', 'General'), ('breaking', 'Breaking News'), ('exclusive', 'Exclusive'), ('interview', 'Interview'), ('opinion', 'Opinion')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Main article image', upload_to='news_images/%Y/%m/%d/')),
                ('image_caption', models.CharField(blank=True, help_text='Caption for the main image', max_length=300)),
                ('image_alt_text', models.CharField(blank=True, help_text='SEO-friendly image description', max_length=125)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('featured', 'Featured')], default='draft', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0, help_text='Unique visitor count')),
                ('shares', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=1, help_text='Estimated reading time in minutes')),
                ('meta_title', models.CharField(blank=True, help_text='Override default title for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines', max_length=320)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('is_sticky', models.BooleanField(default=False, help_text='Stick to top in category')),
                ('sticky_until', models.DateTimeField(blank=True, help_text='When to remove sticky status', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Custom Open Graph image for social sharing', upload_to='news_og_images/')),
                ('twitter_image', models.ImageField(blank=True, help_text='Custom Twitter card image', upload_to='news_twitter_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_news', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category')),
                ('related_news', models.ManyToManyField(blank=True, help_text='Manually related articles', to='news.news')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Add tags for better searchability', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ('-publish',),
                'permissions': [('can_publish_news', 'Can publish news'), ('can_feature_news', 'Can feature news')],
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='news.news')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, help_text='Optional website URL')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('spam_score', models.FloatField(default=0.0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='news_catego_slug_0c9c67_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='news_catego_is_feat_2031f2_idx'),
        ),
        migrations.AddIndex(
            model_name='newsview',
            index=models.Index(fields=['news', '-viewed_at'], name='news_newsvi_news_id_a2321d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsbookmark',
            unique_together={('user', 'news')},
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-publish', 'status'], name='news_news_publish_8670d4_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug', 'publish'], name='news_news_slug_3ff846_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', 'status'], name='news_news_categor_caf58c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured', '-publish'], name='news_news_is_feat_2ffec7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['news', 'active', '-created'], name='news_commen_news_id_1d20f4_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['email'], name='news_commen_email_903664_idx'),
        ),
    ]
